server.port = 0
spring.application.name=microservicio2

eureka.instance.instance-id=${spring.application.name}:${random.uuid}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.default-zone= http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/database2?charSet=UTF-8
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

logging.file.name=logs/microservicio2.log
